// neoprompts/src/components/PromptModal.tsx
'use client';

import { useState, useEffect } from 'react';
import { Prompt } from '@/lib/db';
import { useCollections, useTags } from '@/lib/hooks';
import { randomTagColor } from '@/lib/utils';

interface PromptModalProps {
  prompt: Prompt | null;
  isOpen: boolean;
  onClose: () => void;
  onSave: (data: Omit<Prompt, 'id' | 'copyCount' | 'lastCopiedAt' | 'createdAt' | 'updatedAt'>) => void;
  defaultCollectionId?: string | null;
}

export default function PromptModal({
  prompt,
  isOpen,
  onClose,
  onSave,
  defaultCollectionId,
}: PromptModalProps) {
  const { collections } = useCollections();
  const { tags: allTags, addTag } = useTags();

  const [title, setTitle] = useState('');
  const [template, setTemplate] = useState('');
  const [description, setDescription] = useState('');
  const [collectionId, setCollectionId] = useState<string | null>(null);
  const [tags, setTags] = useState<string[]>([]);
  const [isFavorite, setIsFavorite] = useState(false);
  const [newTag, setNewTag] = useState('');

  // Reset form when modal opens/closes
  useEffect(() => {
    if (isOpen) {
      if (prompt) {
        setTitle(prompt.title);
        setTemplate(prompt.template);
        setDescription(prompt.description);
        setCollectionId(prompt.collectionId);
        setTags(prompt.tags);
        setIsFavorite(prompt.isFavorite);
      } else {
        setTitle('');
        setTemplate('');
        setDescription('');
        setCollectionId(defaultCollectionId ?? null);
        setTags([]);
        setIsFavorite(false);
      }
    }
  }, [isOpen, prompt, defaultCollectionId]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim() || !template.trim()) return;

    onSave({
      title: title.trim(),
      template: template.trim(),
      description: description.trim(),
      collectionId,
      tags,
      isFavorite,
    });
    onClose();
  };

  const handleAddTag = async () => {
    const tagName = newTag.trim();
    if (!tagName) return;

    // Check if tag already exists
    const existing = allTags.find(t => t.name.toLowerCase() === tagName.toLowerCase());
    if (!existing) {
      await addTag(tagName, randomTagColor());
    }

    if (!tags.includes(tagName)) {
      setTags([...tags, tagName]);
    }
    setNewTag('');
  };

  const removeTag = (tagToRemove: string) => {
    setTags(tags.filter(t => t !== tagToRemove));
  };

  const toggleExistingTag = (tagName: string) => {
    if (tags.includes(tagName)) {
      setTags(tags.filter(t => t !== tagName));
    } else {
      setTags([...tags, tagName]);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="modal show d-block" tabIndex={-1} onClick={onClose}>
      <div className="modal-dialog modal-lg modal-dialog-centered" onClick={e => e.stopPropagation()}>
        <div className="modal-content glass-modal">
          <div className="modal-header">
            <h5 className="modal-title">{prompt ? 'Edit Prompt' : 'New Prompt'}</h5>
            <button type="button" className="btn-close" onClick={onClose}></button>
          </div>
          <form onSubmit={handleSubmit}>
            <div className="modal-body">
              <div className="mb-3">
                <label className="form-label">Title</label>
                <input
                  type="text"
                  className="form-control"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="Enter prompt title"
                  required
                  autoFocus
                />
              </div>

              <div className="mb-3">
                <label className="form-label">
                  Template
                  <small className="text-muted ms-2">Use {'{{variable}}'} for placeholders</small>
                </label>
                <textarea
                  className="form-control"
                  rows={6}
                  value={template}
                  onChange={(e) => setTemplate(e.target.value)}
                  placeholder="Enter your prompt template..."
                  required
                />
              </div>

              <div className="mb-3">
                <label className="form-label">Description (optional)</label>
                <textarea
                  className="form-control"
                  rows={2}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Brief description of this prompt"
                />
              </div>

              <div className="row mb-3">
                <div className="col-md-6">
                  <label className="form-label">Collection</label>
                  <select
                    className="form-select"
                    value={collectionId || ''}
                    onChange={(e) => setCollectionId(e.target.value || null)}
                  >
                    <option value="">No Collection</option>
                    {collections.map(c => (
                      <option key={c.id} value={c.id}>
                        {c.emoji} {c.name}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="col-md-6">
                  <label className="form-label d-flex align-items-center">
                    Favorite
                    <div className="form-check form-switch ms-auto mb-0">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        checked={isFavorite}
                        onChange={(e) => setIsFavorite(e.target.checked)}
                      />
                    </div>
                  </label>
                </div>
              </div>

              <div className="mb-3">
                <label className="form-label">Tags</label>
                <div className="d-flex gap-2 mb-2">
                  <input
                    type="text"
                    className="form-control"
                    value={newTag}
                    onChange={(e) => setNewTag(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddTag())}
                    placeholder="Add new tag..."
                  />
                  <button
                    type="button"
                    className="btn btn-outline-primary"
                    onClick={handleAddTag}
                  >
                    Add
                  </button>
                </div>

                {/* Selected tags */}
                {tags.length > 0 && (
                  <div className="selected-tags mb-2">
                    {tags.map(tag => (
                      <span key={tag} className="badge bg-primary me-1 mb-1">
                        {tag}
                        <button
                          type="button"
                          className="btn-close btn-close-white ms-1"
                          style={{ fontSize: '0.6em' }}
                          onClick={() => removeTag(tag)}
                        ></button>
                      </span>
                    ))}
                  </div>
                )}

                {/* Existing tags to select from */}
                {allTags.length > 0 && (
                  <div className="existing-tags">
                    <small className="text-muted">Existing tags:</small>
                    <div className="mt-1">
                      {allTags.filter(t => !tags.includes(t.name)).map(tag => (
                        <button
                          key={tag.id}
                          type="button"
                          className="badge bg-secondary me-1 mb-1 border-0"
                          onClick={() => toggleExistingTag(tag.name)}
                          style={{ cursor: 'pointer' }}
                        >
                          + {tag.name}
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </div>
            <div className="modal-footer">
              <button type="button" className="btn btn-outline-secondary" onClick={onClose}>
                Cancel
              </button>
              <button type="submit" className="btn btn-primary">
                {prompt ? 'Save Changes' : 'Create Prompt'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

// supaprompts1/src/components/PromptModal.vue
<script setup>
import { ref, watch, computed } from 'vue'
import { useCollectionsStore } from '@/stores/collections'

const props = defineProps({
  show: Boolean,
  prompt: Object
})

const emit = defineEmits(['close', 'save'])

const collectionsStore = useCollectionsStore()

// Form state
const title = ref('')
const template = ref('')
const description = ref('')
const collectionId = ref(null)
const tagsInput = ref('')
const tags = ref([])
const isFavorite = ref(false)

const isEditing = computed(() => !!props.prompt)

// Reset form when modal opens
watch(() => props.show, (newVal) => {
  if (newVal) {
    if (props.prompt) {
      // Edit mode
      title.value = props.prompt.title || ''
      template.value = props.prompt.template || ''
      description.value = props.prompt.description || ''
      collectionId.value = props.prompt.collection_id || null
      tags.value = props.prompt.tags || []
      isFavorite.value = props.prompt.is_favorite || false
    } else {
      // Create mode
      title.value = ''
      template.value = ''
      description.value = ''
      collectionId.value = collectionsStore.activeCollectionId
      tags.value = []
      isFavorite.value = false
    }
    tagsInput.value = ''
  }
})

function addTag() {
  const tag = tagsInput.value.trim().toLowerCase()
  if (tag && !tags.value.includes(tag)) {
    tags.value.push(tag)
  }
  tagsInput.value = ''
}

function removeTag(tag) {
  tags.value = tags.value.filter(t => t !== tag)
}

function handleTagKeydown(e) {
  if (e.key === 'Enter' || e.key === ',') {
    e.preventDefault()
    addTag()
  }
}

function handleSubmit() {
  if (!title.value.trim() || !template.value.trim()) return

  emit('save', {
    title: title.value.trim(),
    template: template.value.trim(),
    description: description.value.trim() || null,
    collection_id: collectionId.value || null,
    tags: tags.value,
    is_favorite: isFavorite.value
  })
}
</script>

<template>
  <Teleport to="body">
    <div v-if="show" class="modal-backdrop fade show"></div>
    <div
      v-if="show"
      class="modal fade show d-block"
      tabindex="-1"
      @click.self="emit('close')"
    >
      <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header border-0 pb-0">
            <h5 class="modal-title fw-bold">
              <i class="bi me-2" :class="isEditing ? 'bi-pencil' : 'bi-plus-lg'"></i>
              {{ isEditing ? 'Edit Prompt' : 'New Prompt' }}
            </h5>
            <button
              type="button"
              class="btn-close"
              @click="emit('close')"
            ></button>
          </div>
          <form @submit.prevent="handleSubmit">
            <div class="modal-body">
              <!-- Title -->
              <div class="mb-3">
                <label class="form-label fw-medium">Title *</label>
                <input
                  v-model="title"
                  type="text"
                  class="form-control form-control-lg"
                  placeholder="e.g., Blog Post Outline Generator"
                  required
                >
              </div>

              <!-- Template -->
              <div class="mb-3">
                <label class="form-label fw-medium">
                  Template *
                  <span class="text-muted fw-normal ms-2">
                    Use <code>{{variable}}</code> for placeholders
                  </span>
                </label>
                <textarea
                  v-model="template"
                  class="form-control"
                  rows="8"
                  placeholder="Write a blog post outline about {{topic}} for {{audience}}..."
                  required
                ></textarea>
              </div>

              <!-- Description -->
              <div class="mb-3">
                <label class="form-label fw-medium">Description</label>
                <input
                  v-model="description"
                  type="text"
                  class="form-control"
                  placeholder="Brief description of what this prompt does..."
                >
              </div>

              <!-- Collection -->
              <div class="mb-3">
                <label class="form-label fw-medium">Collection</label>
                <select v-model="collectionId" class="form-select">
                  <option :value="null">No Collection</option>
                  <option
                    v-for="collection in collectionsStore.sortedCollections"
                    :key="collection.id"
                    :value="collection.id"
                  >
                    {{ collection.name }}
                  </option>
                </select>
              </div>

              <!-- Tags -->
              <div class="mb-3">
                <label class="form-label fw-medium">Tags</label>
                <div class="tags-input-wrapper">
                  <div class="tags-display mb-2" v-if="tags.length">
                    <span
                      v-for="tag in tags"
                      :key="tag"
                      class="badge bg-primary me-1 mb-1"
                    >
                      {{ tag }}
                      <button
                        type="button"
                        class="btn-close btn-close-white ms-1"
                        style="font-size: 0.5rem;"
                        @click="removeTag(tag)"
                      ></button>
                    </span>
                  </div>
                  <input
                    v-model="tagsInput"
                    type="text"
                    class="form-control"
                    placeholder="Type a tag and press Enter..."
                    @keydown="handleTagKeydown"
                    @blur="addTag"
                  >
                </div>
              </div>

              <!-- Favorite -->
              <div class="mb-3">
                <div class="form-check">
                  <input
                    v-model="isFavorite"
                    type="checkbox"
                    class="form-check-input"
                    id="favoriteCheck"
                  >
                  <label class="form-check-label" for="favoriteCheck">
                    <i class="bi bi-star-fill text-warning me-1"></i>
                    Mark as favorite
                  </label>
                </div>
              </div>
            </div>
            <div class="modal-footer border-0 pt-0">
              <button
                type="button"
                class="btn btn-outline-secondary btn-lg"
                @click="emit('close')"
              >
                Cancel
              </button>
              <button
                type="submit"
                class="btn btn-primary btn-lg"
                :disabled="!title.trim() || !template.trim()"
              >
                <i class="bi bi-check-lg me-2"></i>
                {{ isEditing ? 'Save Changes' : 'Create Prompt' }}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<style scoped>
.modal-content {
  border-radius: 1rem;
  border: none;
  box-shadow: 0 1rem 3rem rgba(0, 0, 0, 0.175);
}

.form-control,
.form-select {
  border-radius: 0.75rem;
}

.form-control-lg {
  font-size: 1.125rem;
}

textarea.form-control {
  font-family: 'SF Mono', 'Monaco', 'Inconsolata', 'Roboto Mono', monospace;
  font-size: 0.9rem;
}

.btn-lg {
  border-radius: 0.75rem;
}

code {
  background: var(--bs-tertiary-bg);
  padding: 0.125rem 0.375rem;
  border-radius: 0.25rem;
  font-size: 0.875em;
}

.tags-display .badge {
  font-size: 0.875rem;
  font-weight: 500;
}
</style>
